(()=>{
'use strict';
const {$,$$,clamp,fmt,compact,money,pct}=window.__ATLAS_UI_HELPERS;
Object.assign(window.AtlasUI.prototype,{
 renderInstrumentList(){const q=$('#instrumentSearch').value.trim().toLowerCase(),rows=this.engine.pairs.filter(p=>!q||p.base.toLowerCase().includes(q)||p.name.toLowerCase().includes(q));$('#instrumentList').innerHTML=rows.map(p=>{const m=this.engine.currentMarket(p.base);return`<button class="instrument-option" data-pair="${p.base}"><span><i class="coin-icon" style="background:${p.color}">${p.icon}</i><span><b>${this.engine.product==='spot'?`${p.base}/USDT`:`${p.base}USDT`}</b><small>${p.name}</small></span></span><span><b>${fmt(m.last,p.decimals)}</b><small class="${m.change>=0?'positive':'negative'}">${pct(m.change)}</small></span></button>`}).join('');$$('[data-pair]').forEach(b=>b.onclick=()=>{this.engine.setPair(b.dataset.pair);this.amountUnit='USDT';this.closeSheet('instrumentSheet');this.renderAll()})},
 renderMarkets(){const q=$('#marketSearch').value.trim().toLowerCase(),rows=this.engine.pairs.filter(p=>!q||p.base.toLowerCase().includes(q)||p.name.toLowerCase().includes(q));$('#marketList').innerHTML=rows.map(p=>{const m=this.engine.currentMarket(p.base);return`<article class="market-item"><div class="coin"><i class="coin-icon" style="background:${p.color}">${p.icon}</i><span><b>${p.base}/USDT</b><small>${p.name}</small></span></div><span><b>${fmt(m.last,p.decimals)}</b><small>${compact(m.volumeQuote)}</small></span><span class="${m.change>=0?'positive':'negative'}"><b>${pct(m.change)}</b></span><button data-market-trade="${p.base}">交易</button></article>`}).join('');$$('[data-market-trade]').forEach(b=>b.onclick=()=>{this.engine.setPair(b.dataset.marketTrade);this.navigateBottom('trade')})},
 renderAssets(){const e=this.engine.equity(),ret=(e.equity-this.engine.account.initial)/this.engine.account.initial*100;$('#assetEquity').textContent=money(e.equity);$('#assetReturn').textContent=pct(ret);$('#assetReturn').className=ret>=0?'positive':'negative';$('#assetCash').textContent=money(this.engine.account.cash);$('#assetPnl').textContent=money(e.unrealized);const ps=Object.values(this.engine.account.positions);$('#assetPositions').innerHTML=ps.length?ps.map(p=>{const px=this.engine.currentMarket(p.base).last||p.avg,pnl=(px-p.avg)*p.qty;return`<article class="asset-position"><header><b>${p.base}/USDT · ${p.type==='spot'?'现货':`${p.leverage}x ${p.qty>0?'多':'空'}`}</b><strong class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${money(pnl)}</strong></header><p>数量 ${fmt(Math.abs(p.qty),6)} · 均价 ${fmt(p.avg,this.engine.pairs.find(x=>x.base===p.base).decimals)} · 现价 ${fmt(px,this.engine.pairs.find(x=>x.base===p.base).decimals)}</p></article>`}).join(''):'<div class="empty-state">当前资产全部为 USDT</div>'},
 renderAnalysis(){const e=this.engine.equity(),ps=Object.values(this.engine.account.positions),exposure=ps.reduce((s,p)=>s+Math.abs(p.qty)*(this.engine.currentMarket(p.base).last||p.avg),0),usage=exposure/Math.max(e.equity,1),risk=Math.round(clamp(usage*40+Math.max(0,-e.unrealized/e.equity*180),0,100)),trades=this.engine.account.trades,win=trades.filter(t=>(t.realized||0)>0).length,realized=trades.reduce((s,t)=>s+(t.realized||0),0);$('#riskScore').textContent=risk;$('.risk-ring').style.setProperty('--risk',`${risk}%`);$('#riskTitle').textContent=risk<30?'风险较低':risk<65?'风险中等':'风险偏高';$('#riskText').textContent=`当前账户风险敞口 ${money(exposure)}，未实现盈亏 ${money(e.unrealized)}。`;const metrics=[['累计收益',pct((e.equity-this.engine.account.initial)/this.engine.account.initial*100)],['已实现盈亏',money(realized)],['交易次数',trades.length],['胜率',trades.length?`${(win/trades.length*100).toFixed(1)}%`:'--']];$('#analysisMetrics').innerHTML=metrics.map(x=>`<article class="metric-card"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('')},
 renderConvert(){const pay=+($('#convertPay')?.value||0),m=this.engine.currentMarket('BTC');if($('#convertReceive'))$('#convertReceive').value=m.last?(pay/m.last).toFixed(6):'';if($('#convertRate'))$('#convertRate').textContent=`1 BTC ≈ ${fmt(m.last,2)} USDT`},
 seedUtility(){const chains=[['Ethereum','网络正常','Gas 低'],['Solana','网络正常','确认快速'],['Bitcoin','网络正常','内存池稳定'],['Base','网络正常','费用较低'],['Arbitrum','网络正常','活跃度高'],['BNB Chain','网络正常','交易稳定']];$('#onchainGrid').innerHTML=chains.map(x=>`<article class="feature-card"><header><div><span>NETWORK</span><h3>${x[0]}</h3></div><b class="positive">${x[1]}</b></header><p>${x[2]}，用于展示链上市场与网络状态聚合能力。</p><button data-feature-action="查看 ${x[0]}">查看详情</button></article>`).join('');const strategies=[['现货网格','震荡行情','模拟运行'],['合约网格','双向捕捉','未启动'],['定投策略','长期积累','模拟运行'],['趋势跟随','顺势执行','未启动'],['智能套利','价差监控','监控中'],['组合再平衡','控制偏离','未启动']];$('#strategyGrid').innerHTML=strategies.map(x=>`<article class="feature-card"><header><div><span>${x[1]}</span><h3>${x[0]}</h3></div><b>${x[2]}</b></header><p>完整展示策略参数、运行状态与模拟收益反馈。</p><button data-feature-action="配置 ${x[0]}">配置策略</button></article>`).join('');$$('[data-feature-action]').forEach(b=>b.onclick=()=>this.toast(`${b.dataset.featureAction}：演示入口已响应`))},
 chartSetting(type){if(type==='fit'){this.chart.fit();this.hideChartInfo();this.closeSheet('indicatorSheet');return}if(type==='ema'){this.chart.options.ema=!this.chart.options.ema;this.chart.setOption('ema',this.chart.options.ema);$('#emaSettingState').textContent=this.chart.options.ema?'显示':'隐藏'}if(type==='volume'){this.chart.options.volume=!this.chart.options.volume;this.chart.setOption('volume',this.chart.options.volume);$('#volumeSettingState').textContent=this.chart.options.volume?'显示':'隐藏'}this.chart.resize()},
 exportReport(){const blob=new Blob([JSON.stringify(this.engine.exportReport(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`atlas-v14-report-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),400);this.closeSheet('moreSheet');this.toast('账户报告已导出')}
});
})();
