(()=>{
'use strict';
const {$,$$,clamp,fmt,compact,money,pct}=window.__ATLAS_UI_HELPERS;
Object.assign(window.AtlasUI.prototype,{
 renderQuote(){const p=this.engine.pair,m=this.engine.currentMarket();$('#instrumentName').textContent=this.engine.product==='spot'?`${p.base}/USDT`:`${p.base}USDT`;$('#bookMidPrice').textContent=fmt(m.last,p.decimals);$('#bookMidUsd').textContent=`≈ ${money(m.last)}`;$('#bookMidChange').textContent=pct(m.change);$('#bookMidChange').className=m.change>=0?'positive':'negative';$('#bookUnit').textContent=`(${p.base})`;this.renderConvert()},
 renderBook(){const p=this.engine.pair,book=this.engine.book,all=[...book.asks,...book.bids],max=Math.max(1,...all.map(x=>x[1]));const rows=(arr,kind)=>arr.map(([px,q])=>`<div class="book-row ${kind}" style="--depth:${Math.max(5,q/max*100)}%;--depth-color:${kind==='ask'?'rgba(243,61,148,.13)':'rgba(120,189,0,.16)'}"><span>${fmt(px,p.decimals)}</span><span>${fmt(q,p.base==='BTC'?5:3)}</span></div>`).join('');$('#bookAsks').innerHTML=rows(book.asks,'ask');$('#bookBids').innerHTML=rows(book.bids,'bid');const bid=book.bids.reduce((s,x)=>s+x[1],0),ask=book.asks.reduce((s,x)=>s+x[1],0),r=bid/(bid+ask||1)*100;$('#buyRatio').textContent=`B ${r.toFixed(0)}%`;$('#sellRatio').textContent=`${(100-r).toFixed(0)}% S`;$('#ratioBar').style.width=`${r}%`},
 sliderAmount(value){const m=this.engine.currentMarket(),cash=this.engine.account.cash,pctv=value/100;if(this.amountUnit==='USDT')return cash*pctv;if(this.engine.product==='spot'&&this.side==='sell'){const pos=this.engine.account.positions[`${this.engine.pair.base}-spot`];return(pos?.qty||0)*pctv}return cash*(this.engine.product==='perp'?this.leverage:1)/Math.max(m.last,1)*pctv},
 renderOrderForm(){const p=this.engine.pair,m=this.engine.currentMarket(),perp=this.engine.product==='perp';$$('#spotSideTabs button').forEach(b=>b.classList.toggle('active',b.dataset.side===this.side));$$('#perpActionTabs button').forEach(b=>b.classList.toggle('active',b.dataset.positionAction===this.positionAction));$('#marginModeText').textContent=this.marginMode==='cross'?'全仓':'逐仓';$('#leverageText').textContent=`${this.leverage}x`;$('#orderTypeText').textContent=this.orderType==='market'?'市价委托':'限价委托';$('#priceRow').classList.toggle('hidden',this.orderType==='market');if(this.orderType==='limit'&&!$('#orderPrice').value)$('#orderPrice').value=m.last.toFixed(p.decimals);$('#amountLabel').textContent=this.amountUnit==='USDT'?'金额':'数量';$('#amountUnitText').textContent=this.amountUnit==='USDT'?'USDT':p.base;const amount=+($('#orderAmount').value||0),price=this.orderType==='market'?m.last:+($('#orderPrice').value||m.last),qty=this.amountUnit==='USDT'?amount/Math.max(price,1):amount,available=this.engine.account.cash;$('#availableBalance').textContent=`${fmt(available,2)} USDT`;let cap;if(perp)cap=available*this.leverage/Math.max(price,1);else if(this.side==='buy')cap=available/Math.max(price,1);else cap=this.engine.account.positions[`${p.base}-spot`]?.qty||0;$('#capacityLabel').textContent=perp?(this.positionAction==='open'?(this.side==='buy'?'可开多':'可开空'):'可平仓'):(this.side==='buy'?'可买':'可卖');$('#capacityValue').textContent=`${fmt(cap,6)} ${p.base}`;let label;if(perp)label=`${this.positionAction==='open'?'开':'平'}${this.side==='buy'?'多':'空'} ${this.leverage}x`;else label=`${this.side==='buy'?'买入':'卖出'} ${p.base}`;const submit=$('#submitOrder');submit.textContent=label;submit.className=`submit-order ${this.side==='buy'?'buy':'sell'}`;$('#secondaryCapacity').textContent=qty>0?`预计数量 ${fmt(qty,6)} ${p.base} · 参考价格 ${fmt(price,p.decimals)}`:'';$('#amountSlider').style.setProperty('--range',`${$('#amountSlider').value}%`)},
 placeOrder(){const amount=+($('#orderAmount').value||0),price=this.orderType==='market'?this.engine.currentMarket().last:+($('#orderPrice').value||0);const result=this.engine.placeOrder({side:this.side,orderType:this.orderType,amount,price,amountUnit:this.amountUnit,positionAction:this.positionAction,leverage:this.engine.product==='perp'?this.leverage:1,marginMode:this.marginMode});this.toast(result.message);if(result.ok){$('#orderAmount').value='';$('#amountSlider').value=0;$('#amountSlider').style.setProperty('--range','0%');this.renderAll()}},
 renderAccount(){const a=this.engine.account,positions=Object.values(a.positions),orders=a.orders,trades=a.trades;$('#positionCount').textContent=positions.length;$('#orderCount').textContent=orders.length;$$('#accountTabs button').forEach(b=>b.classList.toggle('active',b.dataset.accountTab===this.accountTab));let html='';if(this.accountTab==='positions'){html=positions.length?positions.map(p=>{const px=this.engine.currentMarket(p.base).last||p.avg,pnl=(px-p.avg)*p.qty;return`<article class="account-item"><div><h4>${p.base}/USDT · ${p.type==='spot'?'现货':`${p.leverage}x ${p.qty>0?'多':'空'}`}</h4><p>数量 ${fmt(Math.abs(p.qty),6)} · 均价 ${fmt(p.avg,this.engine.pairs.find(x=>x.base===p.base).decimals)}</p></div><aside><strong class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${money(pnl)}</strong><button data-close-position="${p.key}">平仓</button></aside></article>`}).join(''):'<div class="empty-state">暂无持仓</div>'}else if(this.accountTab==='orders'){html=orders.length?orders.map(o=>`<article class="account-item"><div><h4>${o.base}/USDT · ${o.product==='spot'?'现货':'永续'}</h4><p>${o.side==='buy'?'买入/做多':'卖出/做空'} · 限价 ${fmt(o.price,this.engine.pairs.find(x=>x.base===o.base).decimals)}</p></div><aside><strong>${fmt(o.qty,6)}</strong><button data-cancel-order="${o.id}">撤单</button></aside></article>`).join(''):'<div class="empty-state">暂无当前委托</div>'}else{html=trades.length?trades.slice(0,30).map(t=>`<article class="account-item"><div><h4>${t.base}/USDT · ${t.product==='spot'?'现货':'永续'}</h4><p>${new Date(t.filledAt).toLocaleTimeString('zh-CN',{hour12:false})} · ${t.side==='buy'?'买入/做多':'卖出/做空'} ${fmt(t.qty,6)}</p></div><aside><strong>${fmt(t.price,this.engine.pairs.find(x=>x.base===t.base).decimals)}</strong><p>手续费 ${fmt(t.fee,2)}</p></aside></article>`).join(''):'<div class="empty-state">暂无成交记录</div>'}$('#accountList').innerHTML=html;$$('[data-close-position]').forEach(b=>b.onclick=()=>{this.engine.closePosition(b.dataset.closePosition);this.toast('仓位已平')});$$('[data-cancel-order]').forEach(b=>b.onclick=()=>{this.engine.cancelOrder(b.dataset.cancelOrder);this.toast('委托已撤销')})}
});
})();
