(()=>{'use strict';
const V=window.ATLAS_V9X={version:'V9',settings:read('atlas-x-v9-settings',{layout:'standard',density:'comfortable'}),state:{measureMode:false,measureStart:null,measures:read('atlas-x-v9-measures',[])}};
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function h(t,a={},html=''){const n=document.createElement(t);Object.entries(a).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('data-')?n.setAttribute(k,v):n[k]=v);if(html)n.innerHTML=html;return n}
function api(){return window.__ATLAS_V7||{market:typeof market!=='undefined'?market:null,account:typeof account!=='undefined'?account:null,chart:typeof chart!=='undefined'?chart:null}}
function toast9(s){if(typeof toast==='function')toast(s)}function money(n){return Number.isFinite(+n)?'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'--'}function pct(n,d=2){return Number.isFinite(+n)?`${+n>=0?'+':''}${(+n).toFixed(d)}%`:'--'}function compact(n){return Number.isFinite(+n)?new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(+n):'--'}function text(s,v){const e=document.querySelector(s);if(e)e.textContent=v}
Object.assign(V,{read,save,h,api,toast:toast9,money,pct,compact,text});
const extra=[['AVAX','Avalanche','V','avax',3],['LINK','Chainlink','L','link',3],['DOT','Polkadot','●','dot',3],['LTC','Litecoin','Ł','ltc',2],['BCH','Bitcoin Cash','B','bch',2],['TRX','TRON','T','trx',5],['SUI','Sui','S','sui',4],['TON','Toncoin','T','ton',4]].map(([base,name,icon,cls,decimals])=>({base,name,icon,cls,decimals,spotId:`${base}-USDT`,perpId:`${base}-USDT-SWAP`,binance:`${base}USDT`}));
for(const p of extra){if(byBase[p.base])continue;PAIRS.push(p);byBase[p.base]=p;byId[p.spotId]={...p,product:'spot',instId:p.spotId};byId[p.perpId]={...p,product:'perp',instId:p.perpId}}
function workspace(){document.body.classList.remove('v9-layout-standard','v9-layout-scalper','v9-layout-chart','v9-layout-analysis','v9-density-compact','v9-density-comfortable');document.body.classList.add(`v9-layout-${V.settings.layout}`,`v9-density-${V.settings.density}`);document.querySelectorAll('[data-v9-layout]').forEach(b=>b.classList.toggle('active',b.dataset.v9Layout===V.settings.layout));document.querySelectorAll('[data-v9-density]').forEach(b=>b.classList.toggle('active',b.dataset.v9Density===V.settings.density));document.querySelector('#v9LayoutBtn')?.classList.toggle('active',V.settings.layout!=='standard'||V.settings.density==='compact');setTimeout(()=>api().chart?.resize?.(),120)}
function drawer(sel){document.querySelectorAll('.v9-risk-drawer,.v9-pulse-drawer').forEach(x=>{if(!x.matches(sel))x.classList.remove('show')});document.querySelector(sel)?.classList.toggle('show');V.render?.()}
Object.assign(V,{workspace,drawer});
function addUI(){
 document.title='ATLAS X V9｜专业模拟交易终端';const sm=document.querySelector('.brand small');if(sm)sm.textContent='V9 MULTI-MARKET TERMINAL';const demo=document.querySelector('.demo-badge');if(demo)demo.textContent='DEMO · REALTIME · RISK ENGINE';document.querySelector('.v8-version')?.remove();const live=document.querySelector('#livePill');if(live&&!document.querySelector('.v9-badge'))live.after(h('span',{class:'v9-badge'},'<i></i> V9 PRO'));
 const actions=document.querySelector('.top-actions'),focus=document.querySelector('#focusBtn');if(actions&&!document.querySelector('#v9LayoutBtn')){const lag=h('span',{id:'v9Latency',class:'v9-latency'},'<i></i><span>数据延迟 --</span>'),pulse=h('button',{id:'v9PulseBtn',class:'v9-toolbar-btn'},'市场脉搏'),layout=h('button',{id:'v9LayoutBtn',class:'v9-toolbar-btn'},'工作区');actions.insertBefore(lag,focus);actions.insertBefore(pulse,focus);actions.insertBefore(layout,focus);pulse.onclick=()=>drawer('#v9PulseDrawer');layout.onclick=()=>{const p=document.querySelector('#v9LayoutPopover'),r=layout.getBoundingClientRect();p.style.top=`${r.bottom+6}px`;p.style.right=`${Math.max(8,innerWidth-r.right)}px`;p.classList.toggle('show')}}
 if(!document.querySelector('#v9LayoutPopover')){const p=h('section',{id:'v9LayoutPopover',class:'v9-popover'},`<div class="v9-pop-head"><div><strong>专业工作区</strong><small>布局与信息密度</small></div><button data-v9-close>×</button></div><div class="v9-layout-list"><button class="v9-layout-option" data-v9-layout="standard"><b>标准交易</b><small>完整行情、图表、盘口和下单</small></button><button class="v9-layout-option" data-v9-layout="scalper"><b>短线执行</b><small>强化盘口与订单</small></button><button class="v9-layout-option" data-v9-layout="chart"><b>图表交易</b><small>扩大图表并保留下单</small></button><button class="v9-layout-option" data-v9-layout="analysis"><b>行情分析</b><small>聚焦图表与微观结构</small></button></div><div class="v9-density"><span>界面密度</span><div class="v9-segment"><button data-v9-density="comfortable">舒适</button><button data-v9-density="compact">紧凑</button></div></div>`);document.body.append(p);p.querySelector('[data-v9-close]').onclick=()=>p.classList.remove('show');p.querySelectorAll('[data-v9-layout]').forEach(b=>b.onclick=()=>{V.settings.layout=b.dataset.v9Layout;workspace();save('atlas-x-v9-settings',V.settings)});p.querySelectorAll('[data-v9-density]').forEach(b=>b.onclick=()=>{V.settings.density=b.dataset.v9Density;workspace();save('atlas-x-v9-settings',V.settings)});document.addEventListener('click',e=>{if(!e.target.closest('#v9LayoutPopover')&&!e.target.closest('#v9LayoutBtn'))p.classList.remove('show')})}
 const pairbar=document.querySelector('.pairbar');if(pairbar&&!document.querySelector('#v9RiskStrip')){const s=h('section',{id:'v9RiskStrip',class:'v9-risk-strip'},`<div class="v9-risk-item" id="v9MarginUsage"><span>保证金占用</span><strong>0.00%</strong><small>账户权益</small></div><div class="v9-risk-item" id="v9Maintenance"><span>维持保证金</span><strong>$0.00</strong><small>模拟估算</small></div><div class="v9-risk-item" id="v9LiqBuffer"><span>最近强平距离</span><strong>--</strong><small>当前仓位</small></div><div class="v9-risk-item" id="v9NetExposure"><span>净方向敞口</span><strong>$0.00</strong><small>现货与永续</small></div><div class="v9-risk-item" id="v9Var"><span>1日 VaR 95%</span><strong>$0.00</strong><small>波动近似</small></div><button class="v9-risk-item v9-risk-open" id="v9RiskOpen"><span>风险中心</span><strong>查看压力测试 →</strong><small>仓位与强平诊断</small></button>`);pairbar.after(s);document.querySelector('#v9RiskOpen').onclick=()=>drawer('#v9RiskDrawer');const m=h('section',{id:'v9MobilePulse',class:'v9-mobile-pulse'},`<div><span>价差</span><b id="v9MobileSpread">--</b></div><div><span>盘口</span><b id="v9MobileImbalance">--</b></div><div><span>风险</span><b id="v9MobileRisk">--</b></div><div><span>延迟</span><b id="v9MobileLatency">--</b></div>`);s.after(m)}
 const tabs=document.querySelector('.market-panel .market-tabs');if(tabs&&!document.querySelector('#v9Microbar'))tabs.after(h('section',{id:'v9Microbar',class:'v9-microbar'},`<div><span>价差 / BPS</span><b id="v9SpreadBps">--</b></div><div><span>盘口失衡</span><b id="v9BookImbalance">--</b><div class="v9-imbalance"><i id="v9ImbalanceNeedle" style="left:50%"></i></div></div><div><span>前10档流动性</span><b id="v9TopLiquidity">--</b></div><div><span>主动成交压力</span><b id="v9TradePressure">--</b></div><div><span>预计市场冲击</span><b id="v9MarketImpact">--</b></div>`));
 addDrawers();workspace();
}
function addDrawers(){if(document.querySelector('#v9RiskDrawer'))return;const risk=h('aside',{id:'v9RiskDrawer',class:'v9-risk-drawer'},`<div class="v9-drawer-head"><div><span>PORTFOLIO RISK ENGINE</span><h2>实时风险中心</h2></div><button data-v9-drawer-close>×</button></div><div class="v9-drawer-body"><div class="v9-risk-hero"><div class="v9-risk-gauge" id="v9RiskGauge"><div><strong id="v9RiskScore">0</strong><small>/100 综合风险</small></div></div><div class="v9-risk-copy"><h3 id="v9RiskTitle">账户风险较低</h3><p id="v9RiskSummary">正在计算仓位、保证金、波动率与强平缓冲。</p></div></div><section class="v9-section"><div class="v9-section-head"><strong>压力测试</strong><small>所有资产同步波动</small></div><div id="v9StressList"></div></section><section class="v9-section"><div class="v9-section-head"><strong>仓位风险明细</strong><small>强平价为模拟估算</small></div><div id="v9PositionRiskList"></div></section><div class="v9-risk-actions"><button id="v9ExportRisk">导出风险报告</button><button class="primary" id="v9ReduceRisk">降低25%永续敞口</button></div></div>`),pulse=h('aside',{id:'v9PulseDrawer',class:'v9-pulse-drawer'},`<div class="v9-drawer-head"><div><span>MARKET MICROSTRUCTURE</span><h2>市场脉搏</h2></div><button data-v9-drawer-close>×</button></div><div class="v9-drawer-body"><div class="v9-pulse-hero"><article class="v9-pulse-card"><span>市场广度</span><strong id="v9BreadthText">--</strong><small id="v9BreadthSub">上涨 / 总资产</small><div class="v9-breadth"><i id="v9BreadthBar" style="width:50%"></i></div></article><article class="v9-pulse-card"><span>平均波动</span><strong id="v9AverageVol">--</strong><small>主流资产绝对涨跌</small></article><article class="v9-pulse-card"><span>总成交额</span><strong id="v9TotalVolume">--</strong><small>当前产品市场</small></article><article class="v9-pulse-card"><span>实时数据源</span><strong id="v9DataSource">--</strong><small id="v9DataAge">等待数据</small></article></div><section class="v9-section"><div class="v9-section-head"><strong>领先与落后资产</strong><small>实时排序</small></div><div id="v9LeaderList"></div></section><section class="v9-section"><div class="v9-section-head"><strong>当前交易对微观结构</strong><small>盘口与主动成交</small></div><div id="v9MicroDetail"></div></section></div>`);document.body.append(risk,pulse,h('div',{id:'v9StaleBanner',class:'v9-stale-banner'},'实时行情更新变慢，终端正在自动切换备用线路。'));document.querySelectorAll('[data-v9-drawer-close]').forEach(b=>b.onclick=()=>b.closest('aside').classList.remove('show'))}
V.addUI=addUI;
})();
