(()=>{'use strict';const V=window.ATLAS_V9X,KEY='atlas-x-v9-measures';
function addTools(){const wrap=document.querySelector('.v8-chart-tools')||document.querySelector('.indicator-tools');if(!wrap||document.querySelector('#v9MeasureBtn'))return;const a=V.h('button',{id:'v9MeasureBtn',class:'v9-measure-btn',title:'点击图表两点测量涨跌与时间'},'测距'),b=V.h('button',{id:'v9ClearMeasure',title:'清除测距'},'清测');wrap.append(a,b);a.onclick=()=>mode(!V.state.measureMode);b.onclick=()=>{V.state.measures=[];V.save(KEY,V.state.measures);draw();V.toast('测距标记已清除')}}
function initLayer(){const host=document.querySelector('#chartHost');if(!host||document.querySelector('#v9MeasureLayer'))return;const c=V.h('canvas',{id:'v9MeasureLayer',class:'v9-measure-layer'}),tip=V.h('div',{id:'v9MeasureTip',class:'v9-measure-tip'},'点击图表选择测量起点');host.append(c,tip);c.addEventListener('pointerdown',point);new ResizeObserver(resize).observe(host);resize()}
function resize(){const c=document.querySelector('#v9MeasureLayer'),host=document.querySelector('#chartHost');if(!c||!host)return;const r=host.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);c.style.width=r.width+'px';c.style.height=r.height+'px';c.dataset.dpr=d;draw()}
function mode(on){V.state.measureMode=on;V.state.measureStart=null;document.querySelector('#v9MeasureLayer')?.classList.toggle('active',on);document.querySelector('#v9MeasureBtn')?.classList.toggle('active',on);const tip=document.querySelector('#v9MeasureTip');tip?.classList.toggle('show',on);if(tip&&on){tip.textContent='点击图表选择测量起点';tip.style.left='50%';tip.style.top='56px'}}
function point(e){if(!V.state.measureMode)return;const ch=V.api().chart,c=e.currentTarget,r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,price=ch?.candles?.coordinateToPrice(y),tv=ch?.chart?.timeScale().coordinateToTime(x);if(price==null||tv==null)return;const t=typeof tv==='number'?tv:new Date(tv.year,tv.month-1,tv.day).getTime()/1000,p={time:t,price};if(!V.state.measureStart){V.state.measureStart=p;const tip=document.querySelector('#v9MeasureTip');if(tip)tip.textContent='再点击一次选择测量终点'}else{V.state.measures.push({a:V.state.measureStart,b:p});V.save(KEY,V.state.measures);mode(false);draw();V.toast('测距标记已添加')}}
function draw(){const c=document.querySelector('#v9MeasureLayer');if(!c)return;const d=+c.dataset.dpr||1,ctx=c.getContext('2d'),w=c.width/d,h=c.height/d,ch=V.api().chart;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(!ch?.chart||!ch.candles)return;ctx.font='10px -apple-system,sans-serif';for(const m of V.state.measures){const x1=ch.chart.timeScale().timeToCoordinate(m.a.time),x2=ch.chart.timeScale().timeToCoordinate(m.b.time),y1=ch.candles.priceToCoordinate(m.a.price),y2=ch.candles.priceToCoordinate(m.b.price);if([x1,x2,y1,y2].some(v=>v==null))continue;const up=m.b.price>=m.a.price,col=up?'#52e2ba':'#ff6378',change=(m.b.price-m.a.price)/m.a.price*100,sec=Math.abs(m.b.time-m.a.time),duration=sec>=86400?`${(sec/86400).toFixed(1)}天`:sec>=3600?`${(sec/3600).toFixed(1)}小时`:`${Math.max(1,Math.round(sec/60))}分钟`;ctx.strokeStyle=col;ctx.fillStyle=up?'rgba(82,226,186,.08)':'rgba(255,99,120,.08)';ctx.setLineDash([5,4]);ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.fillRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const text=`${change>=0?'+':''}${change.toFixed(2)}% · ${duration}`,tw=ctx.measureText(text).width+12,tx=Math.min(w-tw-4,Math.max(4,(x1+x2)/2-tw/2)),ty=Math.max(15,Math.min(h-5,Math.min(y1,y2)-7));ctx.fillStyle='rgba(7,11,17,.9)';ctx.fillRect(tx,ty-13,tw,17);ctx.fillStyle=col;ctx.fillText(text,tx+6,ty)}}
function patch(){if(typeof ChartController==='undefined'||ChartController.prototype.__v9)return;ChartController.prototype.__v9=true;const i=ChartController.prototype.init,r=ChartController.prototype.resize,s=ChartController.prototype.setData,u=ChartController.prototype.update;ChartController.prototype.init=function(){const x=i.apply(this,arguments);setTimeout(initLayer,0);return x};ChartController.prototype.resize=function(){const x=r.apply(this,arguments);setTimeout(resize,0);return x};ChartController.prototype.setData=function(){const x=s.apply(this,arguments);setTimeout(draw,0);return x};ChartController.prototype.update=function(){const x=u.apply(this,arguments);setTimeout(draw,0);return x}}
patch();Object.assign(V,{addMeasureTools:addTools,measureMode:mode,drawMeasures:draw});
})();
