(()=>{'use strict';const V=window.ATLAS_V9X;
function metrics(){const {market,account}=V.api();if(!market||!account)return null;const snap=account.snapshot(),base=account.metrics(),positions=Object.values(snap.positions||{});let margin=0,maintenance=0,net=0,varSq=0,minLiq=Infinity;const details=[];for(const p of positions){const md=market.get(p.instId),px=md.last||p.avg,qty=p.qty||0,notional=Math.abs(qty)*px,vol=Math.max(.01,md.high&&md.low&&px?(md.high-md.low)/px/4:.02);net+=qty*px;varSq+=(notional*vol)**2;if(p.type==='perp'){margin+=p.margin||0;maintenance+=notional*.005;const lev=Math.max(1,p.leverage||1),liq=qty>0?p.avg*(1-.88/lev):p.avg*(1+.88/lev),dist=Math.abs(px-liq)/Math.max(px,1)*100;minLiq=Math.min(minLiq,dist);details.push({...p,px,notional,liq,dist,vol})}else details.push({...p,px,notional,liq:null,dist:null,vol})}const equity=Math.max(1,snap.equity),usage=margin/equity*100,var95=Math.sqrt(varSq)*1.65,liqBuffer=Number.isFinite(minLiq)?minLiq:null,risk=Math.round(Math.min(100,base.risk+Math.min(20,usage*.2)+Math.min(18,var95/equity*180)+(liqBuffer!==null?Math.max(0,18-liqBuffer):0))),stress=shock=>positions.reduce((s,p)=>s+(p.qty||0)*(market.get(p.instId).last||p.avg)*shock,0);return{snap,base,positions,details,margin,maintenance,net,var95,usage,liqBuffer,risk,stress}}
function item(sel,val,cls=''){const e=document.querySelector(sel);if(!e)return;e.classList.remove('warn','high');if(cls)e.classList.add(cls);const s=e.querySelector('strong');if(s)s.textContent=val}
function render(){const x=metrics();if(!x)return;item('#v9MarginUsage',`${x.usage.toFixed(2)}%`,x.usage>45?'high':x.usage>25?'warn':'');item('#v9Maintenance',V.money(x.maintenance),x.maintenance>x.snap.equity*.15?'high':'');item('#v9LiqBuffer',x.liqBuffer===null?'无永续仓位':`${x.liqBuffer.toFixed(2)}%`,x.liqBuffer!==null&&x.liqBuffer<8?'high':x.liqBuffer!==null&&x.liqBuffer<16?'warn':'');item('#v9NetExposure',V.money(x.net),Math.abs(x.net)>x.snap.equity?'warn':'');item('#v9Var',V.money(x.var95),x.var95>x.snap.equity*.08?'high':x.var95>x.snap.equity*.04?'warn':'');V.text('#v9RiskScore',x.risk);V.text('#v9RiskTitle',x.risk<35?'账户风险较低':x.risk<70?'账户存在中等敞口':'账户风险偏高');V.text('#v9RiskSummary',`权益 ${V.money(x.snap.equity)}，保证金占用 ${x.usage.toFixed(2)}%，1日 VaR 95% 约 ${V.money(x.var95)}。${x.liqBuffer===null?'当前没有永续仓位。':`最近模拟强平缓冲 ${x.liqBuffer.toFixed(2)}%。`}`);const gauge=document.querySelector('#v9RiskGauge'),col=x.risk<35?'var(--green)':x.risk<70?'var(--gold)':'var(--red)';if(gauge)gauge.style.background=`radial-gradient(circle,var(--panel) 57%,transparent 59%),conic-gradient(${col} 0 ${x.risk}%,var(--panel3) ${x.risk}% 100%)`;const shocks=[-.1,-.05,-.02,.02,.05,.1],stress=document.querySelector('#v9StressList');if(stress)stress.innerHTML=shocks.map(s=>{const pnl=x.stress(s);return`<div class="v9-stress-row"><span>市场 ${s>0?'+':''}${(s*100).toFixed(0)}%<small>同步价格冲击</small></span><b class="${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${V.money(pnl)}</b><b>${V.money(x.snap.equity+pnl)}</b></div>`}).join('');const list=document.querySelector('#v9PositionRiskList');if(list)list.innerHTML=x.details.length?x.details.map(p=>`<div class="v9-position-risk-row"><span>${p.base} · ${p.type==='spot'?'现货':`${p.leverage}x ${p.qty>0?'多':'空'}`}<small>名义价值 ${V.money(p.notional)}</small></span><b>${p.liq?`强平 ${Number(p.liq).toLocaleString('en-US',{maximumFractionDigits:6})}`:'无强平'}</b><b class="${p.dist!==null&&p.dist<10?'negative':''}">${p.dist!==null?p.dist.toFixed(2)+'%':'--'}</b></div>`).join(''):'<div class="empty-cell">暂无持仓风险</div>';V.text('#v9MobileRisk',`${x.risk}/100`)}
function exportReport(){const x=metrics();if(!x)return;const report={generatedAt:new Date().toISOString(),version:'V9',equity:x.snap.equity,riskScore:x.risk,marginUsage:x.usage,maintenanceMargin:x.maintenance,var95:x.var95,liquidationBuffer:x.liqBuffer,netExposure:x.net,stress:[-10,-5,-2,2,5,10].map(v=>({shockPct:v,pnl:x.stress(v/100)})),positions:x.details,notice:'模拟风险报告，不构成投资建议。'},blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`atlas-x-v9-risk-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);V.toast('风险报告已导出')}
function reduce(){const {account}=V.api(),ps=Object.values(account?.data?.positions||{}).filter(p=>p.type==='perp');if(!ps.length)return V.toast('当前没有永续仓位');let n=0;for(const p of ps){const r=account.order({instId:p.instId,base:p.base,product:'perp',type:'market',side:p.qty>0?'sell':'buy',amount:Math.abs(p.qty)*.25,leverage:p.leverage||1});if(r.ok)n++}V.toast(n?`已降低 ${n} 个永续仓位的25%敞口`:'当前盘口流动性不足')}
function bind(){document.querySelector('#v9ExportRisk')?.addEventListener('click',exportReport);document.querySelector('#v9ReduceRisk')?.addEventListener('click',reduce)}
Object.assign(V,{riskMetrics:metrics,renderRisk:render,bindRisk:bind});
})();
