(()=>{'use strict';
const desktopLayout=document.createElement('style');desktopLayout.textContent='@media(min-width:761px){.orderbook-panel{grid-row:1!important}.order-panel{grid-row:1!important}.account-panel{grid-column:1/4!important;grid-row:2!important}.book-rows{flex:1!important}.book-row{height:auto!important;min-height:22px!important;flex:1 1 0!important}}';document.head.append(desktopLayout);
const state={price:64407.6,previousPrice:64407.6,timeframe:'1H',side:'buy',orderType:'market',candles:[],pointer:null,position:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=(n,d=1)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function rng(seed){let v=seed%2147483647;if(v<=0)v+=2147483646;return()=> (v=v*16807%2147483647)/2147483647}
function polishStaticUI(){const icons={'通知':'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 7h18s-3 0-3-7"/><path d="M10 19h4"/></svg>','图表设置':'<svg viewBox="0 0 24 24"><path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/></svg>','全屏':'<svg viewBox="0 0 24 24"><path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/></svg>','盘口显示设置':'<svg viewBox="0 0 24 24"><path d="M5 6h14M5 12h14M5 18h14"/></svg>','加入自选':'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.1-5.6-2.9-5.6 2.9 1.1-6.1L3 9.6l6.2-.9z"/></svg>','更多':'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/></svg>'};for(const [label,svg] of Object.entries(icons)){const el=document.querySelector(`[aria-label="${label}"]`);if(el)el.innerHTML=svg}const actions=$('.summary-actions');if(actions&&!$('.market-range'))actions.insertAdjacentHTML('beforebegin','<div class="market-range"><span>24h 区间</span><div><i></i></div><small>62,906.1 — 65,182.3</small></div>')}
function buildCandles(seed=41,count=84){const r=rng(seed),out=[];let close=62000;for(let i=0;i<count;i++){const open=close;close=open+(r()-.46)*470+(i>48?55:20);out.push({open,close,high:Math.max(open,close)+r()*240,low:Math.min(open,close)-r()*220,volume:40+r()*160,time:`${String((i+3)%24).padStart(2,'0')}:00`})}const delta=state.price-out.at(-1).close;out.forEach((c,i)=>{const w=i/(out.length-1);for(const k of ['open','close','high','low'])c[k]+=delta*w});return out}
function ma(data,p){return data.map((_,i)=>{const a=data.slice(Math.max(0,i-p+1),i+1);return a.reduce((t,c)=>t+c.close,0)/a.length})}
function drawChart(){const canvas=$('#chartCanvas'),stage=$('#chartStage');if(!canvas||!stage)return;const rect=stage.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.max(320,Math.floor(rect.width)),h=Math.max(220,Math.floor(rect.height));canvas.width=w*ratio;canvas.height=h*ratio;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;const c=canvas.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);const pad={t:17,r:58,b:29,l:10},vol=Math.min(60,h*.18),bottom=h-pad.b-vol,ch=bottom-pad.t,cw=w-pad.l-pad.r,visible=state.candles.slice(-(w<600?46:68)),max=Math.max(...visible.map(x=>x.high)),min=Math.min(...visible.map(x=>x.low)),range=Math.max(1,max-min),y=p=>pad.t+(max-p)/range*ch,step=cw/visible.length,bar=clamp(step*.58,3,9);c.strokeStyle='#1a2634';c.fillStyle='#617084';c.font='9px ui-monospace,SFMono-Regular,Menlo,monospace';c.lineWidth=1;c.textBaseline='middle';for(let i=0;i<=5;i++){const yy=pad.t+ch/5*i;c.beginPath();c.moveTo(pad.l,yy+.5);c.lineTo(w-pad.r,yy+.5);c.stroke();c.fillText(fmt(max-range/5*i,1),w-pad.r+7,yy)}for(let i=0;i<=6;i++){const xx=pad.l+cw/6*i;c.beginPath();c.moveTo(xx+.5,pad.t);c.lineTo(xx+.5,h-pad.b);c.stroke()}const maxV=Math.max(...visible.map(x=>x.volume));visible.forEach((x,i)=>{const xx=pad.l+step*i+step/2,up=x.close>=x.open,color=up?'#19c99a':'#ff6376';c.strokeStyle=color;c.fillStyle=color;c.beginPath();c.moveTo(Math.round(xx)+.5,y(x.high));c.lineTo(Math.round(xx)+.5,y(x.low));c.stroke();c.globalAlpha=.9;c.fillRect(xx-bar/2,Math.min(y(x.open),y(x.close)),bar,Math.max(1.4,Math.abs(y(x.close)-y(x.open))));c.globalAlpha=.18;const vh=x.volume/maxV*(vol-8);c.fillRect(xx-bar/2,h-pad.b-vh,bar,vh);c.globalAlpha=1});
const line=(arr,color)=>{c.strokeStyle=color;c.lineWidth=1.25;c.beginPath();arr.forEach((p,i)=>{const xx=pad.l+step*i+step/2,yy=y(p);i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.stroke()};line(ma(visible,10),'#4f7cff');line(ma(visible,20),'#c58bf3');c.textAlign='center';c.textBaseline='top';c.fillStyle='#617084';[0,Math.floor((visible.length-1)/3),Math.floor((visible.length-1)*2/3),visible.length-1].forEach(i=>c.fillText(visible[i].time,pad.l+step*i+step/2,h-pad.b+7));const ly=y(state.price),up=state.price>=state.previousPrice;c.strokeStyle=up?'#19c99a':'#ff6376';c.setLineDash([3,3]);c.beginPath();c.moveTo(pad.l,ly+.5);c.lineTo(w-pad.r,ly+.5);c.stroke();c.setLineDash([]);c.fillStyle=up?'#19c99a':'#ff6376';c.fillRect(w-pad.r,ly-9,pad.r,18);c.fillStyle='#06120e';c.font='700 9px ui-monospace,SFMono-Regular,Menlo,monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(fmt(state.price,1),w-pad.r/2,ly);if(Number.isInteger(state.pointer)){const i=clamp(state.pointer,0,visible.length-1),x=pad.l+step*i+step/2,yy=y(visible[i].close);c.strokeStyle='#65758a';c.setLineDash([3,3]);c.beginPath();c.moveTo(x,pad.t);c.lineTo(x,h-pad.b);c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke();c.setLineDash([])}canvas.dataset.count=visible.length;canvas.dataset.step=step;canvas.dataset.left=pad.l}
function buildBook(){const r=rng(Math.round(state.price)),mobile=innerWidth<=760,rows=mobile?10:(innerHeight<1000?8:10),asks=[],bids=[];let at=0,bt=0;for(let i=rows;i>=1;i--){const a=.015+r()*.56;at+=a;asks.push(`<div class="book-row" style="--depth:${20+r()*70}%;--depth-color:rgba(255,99,118,.075)"><span class="ask">${fmt(state.price+i*9.6,1)}</span><span>${a.toFixed(4)}</span><span>${at.toFixed(3)}</span></div>`)}for(let i=1;i<=rows;i++){const a=.015+r()*.56;bt+=a;bids.push(`<div class="book-row" style="--depth:${20+r()*70}%;--depth-color:rgba(25,201,154,.07)"><span class="bid">${fmt(state.price-i*9.4,1)}</span><span>${a.toFixed(4)}</span><span>${bt.toFixed(3)}</span></div>`)}$('#askRows').innerHTML=asks.join('');$('#bidRows').innerHTML=bids.join('');const trades=[],now=Date.now();for(let i=0;i<18;i++){const up=r()>.46,p=state.price+(r()-.5)*34,a=.002+r()*.18,t=new Date(now-i*7000).toLocaleTimeString('zh-CN',{hour12:false});trades.push(`<div class="trade-row"><span class="${up?'positive':'negative'}">${fmt(p,1)}</span><span>${a.toFixed(4)}</span><span>${t}</span></div>`)}$('#tradeRows').innerHTML=trades.join('');$('#mobileTradeRows').innerHTML=trades.join('')}
function estimate(){const amount=Number($('#orderAmount').value||0),price=state.orderType==='limit'?Number($('#limitPrice').value||state.price):state.price;$('#estimatedAmount').textContent=`${(amount/Math.max(price,1)).toFixed(6)} BTC`;$('#estimatedFee').textContent=`${(amount*.0008).toFixed(2)} USDT`}
function setSide(side){state.side=side;$$('#sideTabs [data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===side));const s=$('#submitOrder');s.className=`submit-order ${side}`;s.textContent=`${side==='buy'?'买入':'卖出'} BTC`}
function openSheet(side){setSide(side);document.body.classList.add('trade-sheet-open');$('#sheetBackdrop').hidden=false}
function closeSheet(){document.body.classList.remove('trade-sheet-open');setTimeout(()=>$('#sheetBackdrop').hidden=true,260)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function submit(){const amount=Number($('#orderAmount').value||0);if(amount<=0){toast('请输入模拟下单金额');return}const price=state.orderType==='limit'?Number($('#limitPrice').value||state.price):state.price,qty=amount/price;state.position={side:state.side,price,qty};$('#accountBody').innerHTML=`<tr><td><strong>BTC/USDT</strong></td><td class="${state.side==='buy'?'positive':'negative'}">${state.side==='buy'?'买入':'卖出'}</td><td>${qty.toFixed(6)} BTC</td><td>${fmt(price,1)}</td><td>${fmt(state.price,1)}</td><td class="positive">+0.00 USDT</td><td><button class="close-position" type="button">平仓</button></td></tr>`;$('.account-tabs button span').textContent='1';$('#orderAmount').value='';$('#amountRange').value='0';estimate();toast('模拟订单已成交');closeSheet()}
function updatePrice(){state.previousPrice=state.price;state.price+=(Math.random()>.46?1:-1)*(2+Math.random()*18);const up=state.price>=state.previousPrice;for(const id of ['lastPrice','spreadPrice','mobilePrice'])$(`#${id}`).textContent=fmt(state.price,1);$('#priceUsd').textContent=`≈ $${fmt(state.price,2)}`;$('#limitPrice').value=state.price.toFixed(1);$('#priceChange').className=up?'positive':'negative';const last=state.candles.at(-1);last.close=state.price;last.high=Math.max(last.high,state.price);last.low=Math.min(last.low,state.price);estimate();buildBook();drawChart()}
function pointer(e){const canvas=$('#chartCanvas'),rect=canvas.getBoundingClientRect(),x=(e.touches?.[0]?.clientX??e.clientX)-rect.left,step=Number(canvas.dataset.step||1),left=Number(canvas.dataset.left||0),count=Number(canvas.dataset.count||1);state.pointer=clamp(Math.floor((x-left)/step),0,count-1);const v=state.candles.slice(-count)[state.pointer];if(v){const tip=$('#chartTooltip'),chg=(v.close-v.open)/v.open*100;$('#tooltipTime').textContent=`${state.timeframe} · ${v.time}`;$('#tooltipPrice').textContent=fmt(v.close,1);$('#tooltipChange').textContent=`${chg>=0?'+':''}${chg.toFixed(2)}%`;$('#tooltipChange').className=chg>=0?'positive':'negative';tip.hidden=false;tip.style.left=`${clamp(x+12,8,rect.width-132)}px`;tip.style.top='12px'}drawChart()}
function clearPointer(){state.pointer=null;$('#chartTooltip').hidden=true;drawChart()}
function setMobileView(view){$$('[data-mobile-view]').forEach(b=>b.classList.toggle('active',b.dataset.mobileView===view));$$('[data-mobile-panel]').forEach(p=>p.classList.toggle('mobile-active',p.dataset.mobilePanel===view));requestAnimationFrame(drawChart)}
function bind(){$$('#timeframes button').forEach(b=>b.addEventListener('click',()=>{state.timeframe=b.dataset.timeframe;$$('#timeframes button').forEach(x=>x.classList.toggle('active',x===b));state.candles=buildCandles(b.dataset.timeframe.charCodeAt(0)*19+b.dataset.timeframe.length*31);drawChart()}));$$('#bookTabs button').forEach(b=>b.addEventListener('click',()=>{$$('#bookTabs button').forEach(x=>x.classList.toggle('active',x===b));$$('[data-book-view]').forEach(v=>v.classList.toggle('active',v.dataset.bookView===b.dataset.bookTab))}));$$('[data-mobile-view]').forEach(b=>b.addEventListener('click',()=>setMobileView(b.dataset.mobileView)));$$('[data-mobile-side]').forEach(b=>b.addEventListener('click',()=>openSheet(b.dataset.mobileSide)));$$('#sideTabs [data-side]').forEach(b=>b.addEventListener('click',()=>setSide(b.dataset.side)));$$('#orderTypeTabs button').forEach(b=>b.addEventListener('click',()=>{state.orderType=b.dataset.orderType;$$('#orderTypeTabs button').forEach(x=>x.classList.toggle('active',x===b));$('.limit-field').hidden=state.orderType!=='limit';estimate()}));$('#orderAmount').addEventListener('input',estimate);$('#limitPrice').addEventListener('input',estimate);$('#amountRange').addEventListener('input',e=>{$('#orderAmount').value=e.target.value?(100000*Number(e.target.value)/100).toFixed(2):'';estimate()});$('#submitOrder').addEventListener('click',submit);$('#sheetClose').addEventListener('click',closeSheet);$('#sheetBackdrop').addEventListener('click',closeSheet);$('#chartCanvas').addEventListener('mousemove',pointer);$('#chartCanvas').addEventListener('mouseleave',clearPointer);$('#chartCanvas').addEventListener('touchstart',pointer,{passive:true});$('#chartCanvas').addEventListener('touchmove',pointer,{passive:true});$('#accountBody').addEventListener('click',e=>{if(e.target.closest('.close-position')){$('#accountBody').innerHTML='<tr class="empty-row"><td colspan="7"><div class="empty-state"><span class="empty-icon"><svg viewBox="0 0 24 24"><path d="M4 12h16M12 4v16"/></svg></span><b>暂无持仓</b><small>完成一笔模拟下单后，持仓与实时盈亏会显示在这里。</small></div></td></tr>';$('.account-tabs button span').textContent='0';toast('模拟持仓已平仓')}});let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{buildBook();drawChart()},100)})}
function init(){polishStaticUI();state.candles=buildCandles();buildBook();bind();setMobileView('chart');estimate();requestAnimationFrame(drawChart);setInterval(updatePrice,3600)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();