(()=>{'use strict';const X=window.ATLAS_V10;
function h(tag,cls,html){const n=document.createElement(tag);n.className=cls;if(html)n.innerHTML=html;return n}
function brand(){document.title='ATLAS X V10｜高性能专业交易终端';const small=document.querySelector('.brand small');if(small)small.textContent='V10 ULTRA TERMINAL';document.querySelector('.v9-badge')?.remove();const live=document.querySelector('#livePill');if(live&&!document.querySelector('.v10-badge'))live.after(h('span','v10-badge','<i></i> V10 ULTRA'));const demo=document.querySelector('.demo-badge');if(demo)demo.textContent='DEMO · REALTIME · SMOOTH CHART'}
function chartHeader(){const panel=document.querySelector('#chartPanel'),toolbar=panel?.querySelector('.chart-toolbar');if(!panel||!toolbar||document.querySelector('#v10ChartHeadline'))return;const n=h('div','v10-chart-headline','<div><span>专业图表</span><strong id="v10HeadlinePair">BTC / USDT</strong></div><div class="v10-headline-stats"><span>十字光标 <b>时间 / OHLC / 成交量</b></span><span>图表状态 <b id="v10ChartState">实时连接</b></span><span>渲染模式 <b>RAF 节流</b></span></div>');toolbar.before(n)}
function orderHeader(){const panel=document.querySelector('.order-panel'),tabs=panel?.querySelector('.product-tabs');if(!panel||!tabs||document.querySelector('.v10-order-head'))return;tabs.before(h('div','v10-order-head','<div><span>ORDER ENTRY</span><strong>专业下单</strong></div><div><i></i> 模拟执行</div>'))}
function keyboardHint(){const actions=document.querySelector('.top-actions');if(!actions||document.querySelector('.v10-shortcuts'))return;const b=h('button','v10-shortcuts','快捷键');b.title='⌘K 搜索 · B 买入 · S 卖出 · R 风险 · M 测距';actions.insertBefore(b,document.querySelector('#focusBtn'));b.onclick=()=>{const c=document.querySelector('#command');if(c){document.querySelector('#commandOpen')?.click();setTimeout(()=>{const input=document.querySelector('#commandInput');if(input)input.placeholder='⌘K 搜索 · B 买入 · S 卖出 · R 风险 · M 测距'},50)}}}
function stateUpdates(){const api=window.__ATLAS_V7;if(!api)return;const run=()=>{const p=api.market?.pair?.();const pair=document.querySelector('#v10HeadlinePair'),state=document.querySelector('#v10ChartState');if(pair&&p)pair.textContent=`${p.base} / ${p.product==='spot'?'USDT':'USDT-SWAP'}`;if(state)state.textContent=api.market?.connected?'实时连接':api.market?.source==='CACHE'?'缓存降级':'自动重连';document.body.classList.toggle('v10-market-offline',!api.market?.connected)};api.market?.on?.(type=>{if(['ticker','pair','status','markets'].includes(type))X.schedule?X.schedule(run):run()});run()}
function mobile(){if(!document.querySelector('.mobile-nav')||document.querySelector('#v10MobileChartMeta'))return;const m=h('div','v10-mobile-chart-meta','<span><b>点击K线</b> 查看时间与成交量</span><span><b>双指</b> 缩放图表</span>');m.id='v10MobileChartMeta';document.querySelector('#chartPanel')?.append(m)}
function bind(){brand();chartHeader();orderHeader();keyboardHint();mobile();stateUpdates();document.body.classList.add('v10-ready');setTimeout(()=>window.__ATLAS_V7?.chart?.resize?.(),120)}
Object.assign(X,{bindUI:bind});
})();
