(()=>{'use strict';
const X=window.ATLAS_V11=window.ATLAS_V11||{version:'V11',issues:[]};
const fmt=(n,d=8)=>Number.isFinite(+n)?Number(n).toLocaleString('en-US',{maximumFractionDigits:d}):'--';
const timeValue=t=>{if(typeof t==='number')return t;if(t&&typeof t==='object'&&t.year)return Math.floor(new Date(t.year,t.month-1,t.day).getTime()/1000);const d=new Date(t);return Number.isFinite(d.getTime())?Math.floor(d.getTime()/1000):0};
const formatTime=t=>{const n=timeValue(t);if(!n)return'--';return new Date(n*1000).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).replaceAll('/','-')};
function nearest(data,t){const target=timeValue(t);if(!target||!Array.isArray(data)||!data.length)return null;let lo=0,hi=data.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(+data[mid].time<target)lo=mid+1;else hi=mid}const a=data[lo],b=data[Math.max(0,lo-1)];return !b||Math.abs(+a.time-target)<Math.abs(+b.time-target)?a:b}
function ensureSheet(){const host=document.querySelector('#chartHost');if(!host||document.querySelector('#v11CandleSheet'))return;const sheet=document.createElement('section');sheet.id='v11CandleSheet';sheet.className='v11-candle-sheet';sheet.innerHTML='<button class="v11-sheet-close" aria-label="关闭">×</button><div class="v11-sheet-head"><span id="v11SheetTime">点击单根K线查看完整数据</span><em id="v11SheetState">未选择</em></div><div class="v11-sheet-grid"><span>开盘<b data-v11-o>--</b></span><span>最高<b data-v11-h>--</b></span><span>最低<b data-v11-l>--</b></span><span>收盘<b data-v11-c>--</b></span><span>涨跌<b data-v11-chg>--</b></span><span>成交量<b data-v11-vol>--</b></span></div>';host.append(sheet);sheet.querySelector('.v11-sheet-close').onclick=e=>{e.stopPropagation();sheet.classList.remove('show','pinned');const ch=window.__ATLAS_V7?.chart;try{ch?.chart?.clearCrosshairPosition?.()}catch{}};
 const live=document.createElement('div');live.id='v11LiveLegend';live.className='v11-live-legend';live.innerHTML='<span>O <b data-v11-live-o>--</b></span><span>H <b data-v11-live-h>--</b></span><span>L <b data-v11-live-l>--</b></span><span>C <b data-v11-live-c>--</b></span><span>Vol <b data-v11-live-v>--</b></span>';host.append(live)}
function show(c,t,pinned=true){const sheet=document.querySelector('#v11CandleSheet');if(!sheet||!c)return;const chg=c.open?(c.close-c.open)/c.open*100:0;sheet.querySelector('#v11SheetTime').textContent=formatTime(t||c.time);sheet.querySelector('#v11SheetState').textContent=pinned?'已锁定':'十字光标';sheet.querySelector('[data-v11-o]').textContent=fmt(c.open);sheet.querySelector('[data-v11-h]').textContent=fmt(c.high);sheet.querySelector('[data-v11-l]').textContent=fmt(c.low);sheet.querySelector('[data-v11-c]').textContent=fmt(c.close);const ce=sheet.querySelector('[data-v11-chg]');ce.textContent=`${chg>=0?'+':''}${chg.toFixed(2)}%`;ce.className=chg>=0?'positive':'negative';sheet.querySelector('[data-v11-vol]').textContent=new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:3}).format(c.volume||0);sheet.classList.add('show');sheet.classList.toggle('pinned',pinned);
 const map={o:c.open,h:c.high,l:c.low,c:c.close,v:c.volume||0};for(const [k,v] of Object.entries(map)){const e=document.querySelector(`[data-v11-live-${k}]`);if(e)e.textContent=k==='v'?new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(v):fmt(v)}
}
function bindTap(ch){ensureSheet();const host=document.querySelector('#chartHost');if(!host||!ch?.chart||host.dataset.v11TapBound)return;host.dataset.v11TapBound='1';let start=null,moved=false;
 const down=e=>{if(e.button!=null&&e.button!==0)return;start={x:e.clientX,y:e.clientY,t:performance.now()};moved=false};
 const move=e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)moved=true};
 const up=e=>{if(!start||moved||performance.now()-start.t>800){start=null;return}const r=host.getBoundingClientRect(),x=e.clientX-r.left;if(x<0||x>r.width){start=null;return}const tv=ch.chart.timeScale().coordinateToTime(x),c=nearest(ch.data,tv);start=null;if(!c)return;show(c,c.time,true);try{ch.chart.setCrosshairPosition?.(c.close,c.time,ch.candles)}catch{}if(navigator.vibrate)navigator.vibrate(8)};
 host.addEventListener('pointerdown',down,true);host.addEventListener('pointermove',move,true);host.addEventListener('pointerup',up,true);host.addEventListener('pointercancel',()=>{start=null},true);
 if(matchMedia('(hover:hover)').matches){let frame=0,param=null;ch.chart.subscribeCrosshairMove(p=>{param=p;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const d=param?.seriesData?.get(ch.candles),v=param?.seriesData?.get(ch.volume);if(d)show({...d,volume:v?.value||0},param.time,false)})})}
}
function premium(ch){if(!ch?.chart)return;ch.chart.applyOptions({layout:{fontSize:11},grid:{vertLines:{visible:true,color:'rgba(112,124,143,.12)'},horzLines:{visible:true,color:'rgba(112,124,143,.12)'}},rightPriceScale:{autoScale:true,alignLabels:true,entireTextOnly:true,scaleMargins:{top:.11,bottom:.22}},timeScale:{barSpacing:9,minBarSpacing:3,rightOffset:5,lockVisibleTimeRangeOnResize:true,rightBarStaysOnScroll:true,shiftVisibleRangeOnNewBar:true,timeVisible:true,secondsVisible:false}});ch.candles?.applyOptions({upColor:'#14b889',downColor:'#ec5b72',wickUpColor:'#14b889',wickDownColor:'#ec5b72',borderVisible:false,priceLineStyle:2});
}
function patch(){if(typeof ChartController==='undefined'||ChartController.prototype.__v11chart)return;ChartController.prototype.__v11chart=true;const init=ChartController.prototype.init,set=ChartController.prototype.setData,update=ChartController.prototype.update,resize=ChartController.prototype.resize,restyle=ChartController.prototype.restyle;ChartController.prototype.init=function(){const r=init.apply(this,arguments);setTimeout(()=>{bindTap(this);premium(this)},0);return r};ChartController.prototype.setData=function(data,fit=true){const r=set.call(this,data,fit);setTimeout(()=>{bindTap(this);premium(this);const c=this.data?.at(-1);if(c)show(c,c.time,false)},0);return r};ChartController.prototype.update=function(c){const r=update.call(this,c);setTimeout(()=>{const sheet=document.querySelector('#v11CandleSheet');if(c&&!sheet?.classList.contains('pinned'))show(c,c.time,false)},0);return r};ChartController.prototype.resize=function(){const r=resize.apply(this,arguments);setTimeout(()=>premium(this),0);return r};ChartController.prototype.restyle=function(){const r=restyle.apply(this,arguments);setTimeout(()=>premium(this),0);return r}}
patch();Object.assign(X,{bindTap,showCandle:show,nearestCandle:nearest});
})();
