class MarketEngine{
 constructor(){this.product='spot';this.base='BTC';this.bar='1H';this.markets=new Map();this.candles=[];this.book={asks:[],bids:[]};this.trades=[];this.funding=0;this.mark=0;this.index=0;this.openInterest=0;this.nextFunding=0;this.ws=null;this.reconnect=null;this.poll=null;this.fastPoll=null;this.ping=null;this.connected=false;this.source='OKX';this.lastMessage=0;this.listeners=[]}
 on(fn){this.listeners.push(fn)}emit(type,payload){this.listeners.forEach(fn=>{try{fn(type,payload)}catch(e){console.error(e)}})}
 pair(){const p=byBase[this.base];return{...p,product:this.product,instId:this.product==='spot'?p.spotId:p.perpId}}
 get(id=this.pair().instId){return this.markets.get(id)||{instId:id,last:0,change:0,high:0,low:0,volumeQuote:0,bid:0,ask:0,ts:0}}
 status(ok,label){this.connected=ok;this.emit('status',{ok,label,source:this.source,ts:Date.now()})}
 normTicker(x){const last=+x.last||0,open=+x.open24h||+x.sodUtc0||last;return{instId:x.instId,last,open,high:+x.high24h||0,low:+x.low24h||0,volume:+x.vol24h||0,volumeQuote:+x.volCcy24h||0,change:open?(last-open)/open*100:0,bid:+x.bidPx||0,ask:+x.askPx||0,ts:+x.ts||Date.now()}}
 normCandle(x){return{time:Math.floor(+x[0]/1000),open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]}}
 rows(r=[]){return r.map(x=>[+x[0],+x[1],+x[2]||0]).filter(x=>x[0]&&x[1])}
 async fetchMarkets(){try{const [spot,swap]=await Promise.all([json('https://www.okx.com/api/v5/market/tickers?instType=SPOT'),json('https://www.okx.com/api/v5/market/tickers?instType=SWAP')]);const allowed=new Set(PAIRS.flatMap(p=>[p.spotId,p.perpId]));[...(spot.data||[]),...(swap.data||[])].filter(x=>allowed.has(x.instId)).forEach(x=>this.markets.set(x.instId,this.normTicker(x)));this.source='OKX';this.status(true,'OKX 实时行情');this.emit('markets',this.markets);return true}catch(e){await this.fetchMarketsFallback();return true}}
 async fetchMarketsFallback(){const endpoint=this.product==='spot'?'https://api.binance.com/api/v3/ticker/24hr':'https://fapi.binance.com/fapi/v1/ticker/24hr';const d=await json(endpoint);const map=new Map(d.map(x=>[x.symbol,x]));PAIRS.forEach(p=>{const x=map.get(p.binance);if(!x)return;const id=this.product==='spot'?p.spotId:p.perpId;this.markets.set(id,{instId:id,last:+(x.lastPrice||0),open:+(x.openPrice||0),high:+(x.highPrice||0),low:+(x.lowPrice||0),volume:+(x.volume||0),volumeQuote:+(x.quoteVolume||0),change:+(x.priceChangePercent||0),bid:+(x.bidPrice||0),ask:+(x.askPrice||0),ts:+(x.closeTime||Date.now())})});this.source='BINANCE';this.status(true,'备用实时行情');this.emit('markets',this.markets)}
 async loadCandles(){const id=this.pair().instId;try{const d=await json(`https://www.okx.com/api/v5/market/candles?instId=${encodeURIComponent(id)}&bar=${encodeURIComponent(this.bar)}&limit=300`);if(d.code!=='0')throw new Error('candles');this.candles=(d.data||[]).map(x=>this.normCandle(x)).reverse();this.source='OKX'}catch{const p=this.pair(),base=this.product==='spot'?'https://api.binance.com/api/v3/klines':'https://fapi.binance.com/fapi/v1/klines';const d=await json(`${base}?symbol=${p.binance}&interval=${BINANCE_BAR[this.bar]}&limit=300`);this.candles=d.map(x=>({time:Math.floor(+x[0]/1000),open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]}));this.source='BINANCE'}this.emit('candles',this.candles);return this.candles}
 async loadBook(){const id=this.pair().instId;try{const d=await json(`https://www.okx.com/api/v5/market/books?instId=${encodeURIComponent(id)}&sz=30`);const b=d.data?.[0];this.book={asks:this.rows(b?.asks),bids:this.rows(b?.bids)}}catch{this.book={asks:[],bids:[]}}this.emit('book',this.book);return this.book}
 async loadTrades(){const id=this.pair().instId;try{const d=await json(`https://www.okx.com/api/v5/market/trades?instId=${encodeURIComponent(id)}&limit=80`);this.trades=(d.data||[]).map(x=>({price:+x.px,qty:+x.sz,side:x.side,ts:+x.ts}))}catch{this.trades=[]}this.emit('trades',this.trades);return this.trades}
 async loadDerivatives(){if(this.product!=='perp'){this.funding=0;this.mark=0;this.index=0;this.openInterest=0;this.nextFunding=0;this.emit('derivatives',{});return}const id=this.pair().instId,p=this.pair();try{const [f,m,i,o]=await Promise.all([json(`https://www.okx.com/api/v5/public/funding-rate?instId=${id}`),json(`https://www.okx.com/api/v5/public/mark-price?instType=SWAP&instId=${id}`),json(`https://www.okx.com/api/v5/market/index-tickers?instId=${p.base}-USDT`),json(`https://www.okx.com/api/v5/public/open-interest?instType=SWAP&instId=${id}`)]);this.funding=+(f.data?.[0]?.fundingRate||0);this.nextFunding=+(f.data?.[0]?.nextFundingTime||0);this.mark=+(m.data?.[0]?.markPx||0);this.index=+(i.data?.[0]?.idxPx||0);this.openInterest=+(o.data?.[0]?.oiCcy||o.data?.[0]?.oi||0)}catch{this.funding=0;this.mark=this.get().last;this.index=this.get().last;this.openInterest=0;this.nextFunding=0}this.emit('derivatives',{funding:this.funding,mark:this.mark,index:this.index,openInterest:this.openInterest,nextFunding:this.nextFunding})}
 async init(){await this.fetchMarkets();await Promise.all([this.loadCandles(),this.loadBook(),this.loadTrades(),this.loadDerivatives()]);this.connect();this.startPolling()}
 close(){clearTimeout(this.reconnect);clearInterval(this.poll);clearInterval(this.fastPoll);clearInterval(this.ping);if(this.ws){this.ws.onclose=null;try{this.ws.close()}catch{}}this.ws=null}
 startPolling(){clearInterval(this.poll);clearInterval(this.fastPoll);this.poll=setInterval(()=>this.fetchMarkets().catch(()=>{}),12000);this.fastPoll=setInterval(async()=>{if(Date.now()-this.lastMessage<6500)return;try{await Promise.all([this.fetchMarkets(),this.loadBook(),this.loadTrades(),this.loadDerivatives()]);const d=await json(`https://www.okx.com/api/v5/market/candles?instId=${encodeURIComponent(this.pair().instId)}&bar=${this.bar}&limit=2`);if(d.data?.[0])this.applyCandle(this.normCandle(d.data[0]));this.status(true,'REST 轮询实时')}catch{this.status(false,'网络连接异常')}},4000)}
 connect(){if(this.ws){this.ws.onclose=null;try{this.ws.close()}catch{}}const ws=new WebSocket('wss://ws.okx.com:8443/ws/v5/public');this.ws=ws;let opened=false;const guard=setTimeout(()=>{if(!opened){try{ws.close()}catch{}this.schedule()}},5500);ws.onopen=()=>{opened=true;clearTimeout(guard);this.lastMessage=Date.now();this.status(true,'OKX WebSocket 实时');const args=PAIRS.flatMap(p=>[{channel:'tickers',instId:p.spotId},{channel:'tickers',instId:p.perpId}]);args.push({channel:WS_BAR[this.bar],instId:this.pair().instId},{channel:'books5',instId:this.pair().instId},{channel:'trades',instId:this.pair().instId});ws.send(JSON.stringify({op:'subscribe',args}));this.ping=setInterval(()=>{if(ws.readyState===1)ws.send('ping')},20000)};ws.onmessage=e=>{this.lastMessage=Date.now();if(e.data==='pong')return;let m;try{m=JSON.parse(e.data)}catch{return}const ch=m.arg?.channel;if(!ch||!m.data)return;if(ch==='tickers')this.applyTicker(m.arg.instId,m.data[0]);else if(ch.startsWith('candle'))this.applyCandle(this.normCandle(m.data[0]));else if(ch==='books5'){const b=m.data[0];this.book={asks:this.rows(b.asks),bids:this.rows(b.bids)};this.emit('book',this.book)}else if(ch==='trades'){const inc=m.data.map(x=>({price:+x.px,qty:+x.sz,side:x.side,ts:+x.ts}));this.trades=[...inc,...this.trades].slice(0,100);this.emit('trades',this.trades)}};ws.onerror=()=>this.status(false,'实时连接异常');ws.onclose=()=>{clearTimeout(guard);clearInterval(this.ping);if(this.ws===ws){this.status(false,'正在重连');this.schedule()}}}
 schedule(){clearTimeout(this.reconnect);this.reconnect=setTimeout(()=>this.connect(),2400)}
 applyTicker(id,x){if(!byId[id])return;this.markets.set(id,this.normTicker({...x,instId:id}));this.emit('ticker',{id,data:this.markets.get(id)});this.emit('markets',this.markets)}
 applyCandle(c){const l=this.candles.at(-1);if(l&&l.time===c.time)this.candles[this.candles.length-1]=c;else if(!l||c.time>l.time)this.candles.push(c);if(this.candles.length>400)this.candles.shift();this.emit('candle',c)}
 async select(base,product=this.product){this.base=base;this.product=product;this.book={asks:[],bids:[]};this.trades=[];this.emit('book',this.book);this.emit('trades',this.trades);await Promise.all([this.loadCandles(),this.loadBook(),this.loadTrades(),this.loadDerivatives()]);this.connect();this.emit('pair',this.pair())}
 async setBar(bar){if(!BARS[bar]||bar===this.bar)return;this.bar=bar;await this.loadCandles();this.connect()}
}
